# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b9dd95356b1fa1147671055f746eb238c86905fa5c2342658c985859629b05788d8651da103588a6072c8f918a1a68c13a421dbcf9fb014af8fa5d4d11f868a9

test:
  secret_key_base: df90b39ed77c588a673aaeb6ad71df07aca5ee1ce4d6b877d89d4970489ee2ac9bbe9974fee187a663257487f6c47cb817c8757ada6f76092ba0864eca824ff9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
